### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by FlNDUS** [iternio/ovms-link#27]
Hi there,

After running smoothly since I am using ovms I am getting the following error at the moment:

`(2024-11-20 08:02:47.000+01:00) INFO: Sending telemetry to ABRP {"utc":1732086167,"soc":42.5,"power":0,"speed":0,"lat"<...>"lon"<...>,"is_parked":true,"soh":100,"heading":218.9,"elevation":267.1,"ext_temp":2,"batt_temp":8.75,"voltage":347,"current":0,"odometer":66869,"est_battery_range":52.9873}
I (30415841) ovms-duk-util: [lib/abrp.js:61:log] (2024-11-20 08:02:50.000+01:00) ERROR: ABRP error "SSL error"`

I did not touch ovms or ABRP settings.

I tried:
- rebooting ovms
- setting a new ABRP token in ovms

But the error persists, I first noted it yesterday evening, about 12h ago.

Thanks in advance.

Benedikt

**Comment by jason-abrp** [comment]
Could you try re-running the certificate steps in the [Readme](https://github.com/iternio/ovms-link/blob/dev/README.md)?  We haven't changed certificates recently, but it seems like cloudflare might be auto-cycling certificates for us now.

I'm unfamiliar with what's available on OVMS, perhaps there's a way to automatically reconfigure the certificate when this occurs? It seems pretty annoying to have to do this manually every time it cycles.

**Comment by mdallaire** [comment]
It looks like the cert changed from a Godaddy cert to a Google cert

```
openssl s_client -connect api.iternio.com:443
Connecting to 2606:4700:20::681a:be4
CONNECTED(00000003)
depth=2 C=US, O=Google Trust Services LLC, CN=GTS Root R4
verify return:1
depth=1 C=US, O=Google Trust Services, CN=WE1
verify return:1
depth=0 CN=iternio.com
verify return:1
```

I don't see how OVMS would be able to reconfigure the cert. The "problem" is that OVMS does not include a full standard trusted CA store, probably due to memory constraint.

@jason-abrp can you confirm that `api.iternio.com` is behind Cloudflare and using Cloudflare's certificate? I am asking because I had to do a PR in February because the SSL certs were changed to Godaddy (which is obviously not issued by Cloudflare).

If you can confirm and share which Cloudflare certificate service you are using for your edge certificates, I could submit a PR including the known Cloudflare [trusted root ca](https://developers.cloudflare.com/ssl/reference/certificate-authorities/) which looks like Let's Encrypt and Google. I assume you guys are using either the Universal or Advanced certs.

This way when it expires in December, if it is renewed by the other root authority we won't have to go through this again.

**Comment by mdallaire** [comment]
In the mean time, for anyone having issues, you can add the following to your ovms trustedca folder:
https://valid.r1.roots.globalsign.com/
https://letsencrypt.org/certs/isrg-root-x1-cross-signed.pem
and run `tls trust reload`
Those are the certificates for Cloudflare universal SSL.

**Comment by jason-abrp** [comment]
Thanks for the info! That's really helpful.  We're investigating why the certificate changed, at which proxy layer, and now that we understand more about the limitation for the OVMS's CA store we'll consider if we can come up with a good solution to keep the certificate from changing as frequently on the endpoints OVMS uses.

**Comment by mdallaire** [comment]
The certificate change/renewal is not really a problem as long as we have a relatively steady and small amount of trusted ca to trust. Cloudflare Universal is perfect for this and if you can confirm that this is indeed where the endpoint for api is I will submit a PR for the new certs with an updated readme.

**Comment by FlNDUS** [comment]
@mdallaire thanks your very much, that solution with the certs fixed it for me.
